services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-net

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-net
    restart: unless-stopped

  alert-service:
    build:
      context: ./server
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - mqtt-broker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      mqtt.broker: ${mqtt.broker}
      mqtt.clientId: ${mqtt.clientId}
    restart: unless-stopped
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
